export default [
  {
    name: 'reporter',
    rules: { required: true },
    type: 'Text',
    label: 'Melder',
    placeholder: 'Max Mustermann',
    defaultValue: '',
    errorMsg: 'Der Melder wird benötigt',
  },
  {
    name: 'location',
    rules: { required: true, maxLength: 200 },
    type: 'Text',
    label: 'Standort',
    placeholder: 'Am Waldrand, neben Kirschbaum',
    defaultValue: '',
    errorMsg: 'Der Standort wird benötigt, maximale Länge 200 Zeichen',
  },
  {
    name: 'description',
    rules: { required: false, maxLength: 200 },
    type: 'Text',
    label: 'Beschreibung',
    placeholder: 'Abtransportierung mit Anhänger',
    defaultValue: '',
    multiline: true,
    errorMsg: 'Die maximale Länge beträgt 200 Zeichen',
  },
  {
    name: 'plantName',
    rules: { required: false, maxLength: 200 },
    type: 'Text',
    label: 'Art',
    placeholder: 'Chinesische Samtpappel',
    defaultValue: '',
    multiline: true,
    errorMsg: 'Die maximale Länge beträgt 200 Zeichen',
  },
]